server:
  port: 8102
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.88.128:8761/eureka/,http://192.168.88.128:8760/eureka/
spring:
  application:
    name: zuul-eureka-server-demo
zuul:
  routes:
    client-a:
      path: /client/**
      serviceId: zuul-eureka-client-demo

