server:
  port: 8124
spring:
  application:
    name: skywalking-eureka-server-b
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.88.133:8761/eureka/,http://192.168.88.133:8760/eureka/
