spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wuxiaobo000111/{application}
          username: 2244027504@qq.com
          password: github000111
          search-paths: SC-BOOK-CONFIG
  application:
    name: config-server-placeholders-demo
server:
  port: 8127
logging:
  level:
    root: debug
