server:
  port: 8133
spring:
  application:
    name: swagger-zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.88.133:8761/eureka/,http://192.168.88.133:8760/eureka/
zuul:
  routes:
    client-a:
      path: /a/**
      serviceId: swagger-server-one
    client-b:
      path: /b/**
      serviceId: swagger-server-two