server:
  port: 8120
spring:
  application:
    name: sleuth-eureka-demo-server
  zipkin:
    sender:
      type: rabbit
    service:
      name: sleuth-eureka-demo-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.88.128:8761/eureka/,http://192.168.88.128:8760/eureka/
  zipkin:
    base-url: http://localhost:9411/