spring:
  application:
    name: gateway-eureka-producer
server:
  port: 8142
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.88.133:8761/eureka/,http://192.168.88.133:8760/eureka/