
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wuxiaobo000111/spring-cloud-config.git
          username:
          password:
          search-paths: SC-BOOK-CONFIG
  application:
    name: config-server-demo
server:
  port: 8125