feign-client-config:
  ConnectTimeout: 3000
  ReadTimeout: 3000
server:
  port: 9000
feign:
  httpclient:
    enabled: true
#feign:
#  compression:
#    request:
#      enabled: true
##     配置压缩数据大小的下限
#      min-request-size: 2048
##     配置压缩支持的MIME TYPE
#      mime-types: text/xml,application/xml,application/json
##   是否开启GZIP压缩
#    response:
#      enabled: true
#  client:
#    config:
##    相当于FeignClient注解中的name或者是value属性
#      feignName:
##      连接超时时间
#        connectTimeOut: 5000
##      读超时时间设置
#        readTimeOut: 5000
##      日志级别
#        loggerLevel: full
##      错误解码器
#        errorDecoder: com.bobo.SimpleErrorDecoder
##      配置重试
#        retryer: com.bobo.SimpleRetryer
#        decode404: false
##        编码器
#        encoder: com.bobo.SimpleEncoder
##        解码器
#        decoder: com.bobo.SimpleDecoder
##        contract设置
#        contract: com.bobo.SimpleContract
