server:
  port: 8141
spring:
  application:
    name: gateway-eureka-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.88.133:8761/eureka/,http://192.168.88.133:8760/eureka/
logging:
  level: #调整相关包的 log 级别，以便排查问题
    org.springframework.cloud.gateway: debug
