spring:
  application:
    name: springboot-admin-client-demo
  boot:
    admin:
      client:
        url: http://localhost:8080
server:
  port: 8769

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
