server:
  port: 8139
spring:
  application:
    name: gateway-inner-filter-demo
  cloud:
      gateway:
        routes:
#        - id: add_request_head_route
#          uri: http://localhost:8140
#          filters:
#          - AddRequestHeader=X-Request-Acme, ValueB
#          # 不能少
#          predicates:
#          - After=2017-01-20T17:42:47.789-07:00[America/Denver]
         - id: add_request_parameter_route
           uri: http://localhost:8140
           filters:
           - AddRequestParameter=example, wuxiaobo
           # 不能少
           predicates:
           - After=2017-01-20T17:42:47.789-07:00[America/Denver]
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.88.133:8761/eureka/,http://192.168.88.133:8760/eureka/
logging: ## Spring Cloud Gateway的日志配置
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
