server:
  port: 8138
spring:
  application:
    name: gateway-prodicate-demo
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: http://www.baidu.com
        predicates:
        # 在这里时间之后的都会成功,否则都不会成功，after断言工厂
        - After=2020-06-16T11:50:10.785+08:00[Asia/Shanghai]
      - id: before_route
        uri: http://www.taobao.com
        predicates:
          - Path=/taobao
          - Before=2020-06-16T11:50:10.785+08:00[Asia/Shanghai]
      - id: between_route
        uri: http://www.taobao.com
        predicates:
          - Path=/between
          - name: Between
            args:
              datetime1: 2018-06-16T11:50:10.785+08:00[Asia/Shanghai]
              datetime2: 2020-06-16T11:50:10.785+08:00[Asia/Shanghai]
      - id: cookie_route
        uri: http://localhost:8084
        predicates:
          - Path=/test
          - Cookie=name,wuxiaobo
      - id: header_route
        uri: http://localhost:8084
        predicates:
          - Path=/hello
          - Header=X-Request-Id, \d+
      - id: host_route
        uri: https://jd.com
        predicates:
          - Path=/host
          - Host=**.baidu.com:8080
      - id: method_route
        uri: https://jd.com
        predicates:
          - Path=/method
          - Method=Get
      - id: query_route
        uri: https://baidu.com
        predicates:
          - Path=/query
          - Query=name, wuxiaobo
      discovery:
        locator:
          enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.88.133:8761/eureka/,http://192.168.88.133:8760/eureka/
logging: ## Spring Cloud Gateway的日志配置
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false


