spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wuxiaobo000111/spring-cloud-config
          username:
          password:
          search-paths: SC-BOOK-CONFIG
          repos:
            special:
              pattern: special*
              uri: https://github.com/wuxiaobo000111/special-config
              username:
              password:
              search-path: special-config
  application:
    name: config-server-multiple-demo
server:
  port: 8129
logging:
  level:
    root: debug