server:
  port: 8096
spring:
  application:
    name: hystrix-eureka-cache-producer
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.88.128:8761/eureka/,http://192.168.88.128:8760/eureka/
